### PR TITLE
Update Search.java

### PR DESCRIPTION
**Pull request by axelsvegerud**
Updated to readable code. hihihi

### CODE REVIEW

**Review by AndrejSimeunovic — COMMENTED** [review]
?

**Comment by axelsvegerud** [comment]
Akta dig

**Comment by AndrejSimeunovic** [comment]
hejsan

**Review by AndrejSimeunovic — APPROVED** [review]
nice job mate!

**Review by urostripunovic — COMMENTED** [review]
Hmmmm idk about that one fam

**Review by urostripunovic — COMMENTED** [review]
hihihi

**Pull request merged**
